version: "3.9"

services:
  app_node_backend:
    image: app_node_backend
    build:
      context: ./app_node_backend
      dockerfile: Dockerfile
    container_name: app_node_backend
    ports:
      - "4001:3000"
    environment:
      - PORT=3000
      - DBHOST=mongodb://db:27017
      - DBNAME=app_node_backend
    restart: "no"

  db:
    image: mongo
    container_name: db
    ports:
      - "4000:27017"
    restart: always
